import {Product, Category} from '../models/Product';
import {User} from '../models/User';
import {Address} from '../models/Address';
import {ShippingMethod} from '../models/Order';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic White Sneakers',
    description:
      'Premium leather sneakers with comfortable cushioning. Perfect for everyday wear with a timeless design that goes with any outfit.',
    price: 89.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    ],
    category: 'Footwear',
    brand: 'UrbanStep',
    variants: [
      {id: 'v1', type: 'size', name: 'Size', value: '8', priceModifier: 0, inStock: true},
      {id: 'v2', type: 'size', name: 'Size', value: '9', priceModifier: 0, inStock: true},
      {id: 'v3', type: 'size', name: 'Size', value: '10', priceModifier: 0, inStock: true},
      {id: 'v4', type: 'size', name: 'Size', value: '11', priceModifier: 0, inStock: false},
      {id: 'v5', type: 'color', name: 'Color', value: 'White', priceModifier: 0, inStock: true},
      {id: 'v6', type: 'color', name: 'Color', value: 'Black', priceModifier: 10, inStock: true},
    ],
    inStock: true,
    stockCount: 50,
    dimensions: {width: 12, height: 5, depth: 4},
    weight: 0.8,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Wireless Bluetooth Headphones',
    description:
      'High-quality over-ear headphones with active noise cancellation, 30-hour battery life, and premium sound quality.',
    price: 199.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400',
    ],
    category: 'Electronics',
    brand: 'SoundMax',
    variants: [
      {id: 'v7', type: 'color', name: 'Color', value: 'Black', priceModifier: 0, inStock: true},
      {id: 'v8', type: 'color', name: 'Color', value: 'Silver', priceModifier: 20, inStock: true},
      {id: 'v9', type: 'color', name: 'Color', value: 'Rose Gold', priceModifier: 30, inStock: true},
    ],
    inStock: true,
    stockCount: 30,
    dimensions: {width: 8, height: 7, depth: 3},
    weight: 0.35,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description:
      'Soft and sustainable organic cotton t-shirt. Ethically sourced and environmentally friendly.',
    price: 34.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    ],
    category: 'Clothing',
    brand: 'EcoWear',
    variants: [
      {id: 'v10', type: 'size', name: 'Size', value: 'S', priceModifier: 0, inStock: true},
      {id: 'v11', type: 'size', name: 'Size', value: 'M', priceModifier: 0, inStock: true},
      {id: 'v12', type: 'size', name: 'Size', value: 'L', priceModifier: 0, inStock: true},
      {id: 'v13', type: 'size', name: 'Size', value: 'XL', priceModifier: 5, inStock: true},
      {id: 'v14', type: 'color', name: 'Color', value: 'White', priceModifier: 0, inStock: true},
      {id: 'v15', type: 'color', name: 'Color', value: 'Navy', priceModifier: 0, inStock: true},
      {id: 'v16', type: 'color', name: 'Color', value: 'Forest Green', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 100,
    weight: 0.2,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '4',
    name: 'Smart Watch Pro',
    description:
      'Advanced fitness tracking, heart rate monitoring, GPS, and 7-day battery life. Water resistant up to 50m.',
    price: 299.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    ],
    category: 'Electronics',
    brand: 'TechFit',
    variants: [
      {id: 'v17', type: 'size', name: 'Size', value: '40mm', priceModifier: 0, inStock: true},
      {id: 'v18', type: 'size', name: 'Size', value: '44mm', priceModifier: 30, inStock: true},
      {id: 'v19', type: 'color', name: 'Color', value: 'Space Gray', priceModifier: 0, inStock: true},
      {id: 'v20', type: 'color', name: 'Color', value: 'Silver', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 25,
    dimensions: {width: 1.5, height: 1.7, depth: 0.4},
    weight: 0.05,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Leather Messenger Bag',
    description:
      'Handcrafted genuine leather messenger bag with laptop compartment. Perfect for work or travel.',
    price: 149.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    ],
    category: 'Accessories',
    brand: 'CraftLeather',
    variants: [
      {id: 'v21', type: 'color', name: 'Color', value: 'Brown', priceModifier: 0, inStock: true},
      {id: 'v22', type: 'color', name: 'Color', value: 'Black', priceModifier: 0, inStock: true},
      {id: 'v23', type: 'color', name: 'Color', value: 'Tan', priceModifier: 20, inStock: true},
    ],
    inStock: true,
    stockCount: 15,
    dimensions: {width: 15, height: 11, depth: 4},
    weight: 1.2,
    createdAt: '2024-01-25T10:00:00Z',
  },
  {
    id: '6',
    name: 'Yoga Mat Premium',
    description:
      'Extra thick eco-friendly yoga mat with carrying strap. Non-slip surface for all types of yoga.',
    price: 59.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
    ],
    category: 'Sports',
    brand: 'ZenFit',
    variants: [
      {id: 'v24', type: 'color', name: 'Color', value: 'Purple', priceModifier: 0, inStock: true},
      {id: 'v25', type: 'color', name: 'Color', value: 'Blue', priceModifier: 0, inStock: true},
      {id: 'v26', type: 'color', name: 'Color', value: 'Green', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 40,
    dimensions: {width: 68, height: 24, depth: 0.3},
    weight: 1.5,
    createdAt: '2024-02-05T10:00:00Z',
  },
  {
    id: '7',
    name: 'Stainless Steel Water Bottle',
    description:
      'Double-wall vacuum insulated bottle keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 29.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    ],
    category: 'Sports',
    brand: 'HydroLife',
    variants: [
      {id: 'v27', type: 'size', name: 'Size', value: '500ml', priceModifier: 0, inStock: true},
      {id: 'v28', type: 'size', name: 'Size', value: '750ml', priceModifier: 10, inStock: true},
      {id: 'v29', type: 'size', name: 'Size', value: '1L', priceModifier: 15, inStock: true},
      {id: 'v30', type: 'color', name: 'Color', value: 'Silver', priceModifier: 0, inStock: true},
      {id: 'v31', type: 'color', name: 'Color', value: 'Matte Black', priceModifier: 5, inStock: true},
    ],
    inStock: true,
    stockCount: 80,
    weight: 0.4,
    createdAt: '2024-01-30T10:00:00Z',
  },
  {
    id: '8',
    name: 'Wireless Charging Pad',
    description:
      'Fast wireless charging for all Qi-enabled devices. Sleek minimalist design with LED indicator.',
    price: 39.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=400',
    ],
    category: 'Electronics',
    brand: 'PowerTech',
    variants: [
      {id: 'v32', type: 'color', name: 'Color', value: 'White', priceModifier: 0, inStock: true},
      {id: 'v33', type: 'color', name: 'Color', value: 'Black', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 60,
    dimensions: {width: 4, height: 4, depth: 0.3},
    weight: 0.1,
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '9',
    name: 'Denim Jacket Classic',
    description:
      'Timeless denim jacket with modern fit. Features chest pockets and button closure.',
    price: 79.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400',
    ],
    category: 'Clothing',
    brand: 'DenimCo',
    variants: [
      {id: 'v34', type: 'size', name: 'Size', value: 'S', priceModifier: 0, inStock: true},
      {id: 'v35', type: 'size', name: 'Size', value: 'M', priceModifier: 0, inStock: true},
      {id: 'v36', type: 'size', name: 'Size', value: 'L', priceModifier: 0, inStock: true},
      {id: 'v37', type: 'size', name: 'Size', value: 'XL', priceModifier: 5, inStock: true},
      {id: 'v38', type: 'color', name: 'Color', value: 'Light Blue', priceModifier: 0, inStock: true},
      {id: 'v39', type: 'color', name: 'Color', value: 'Dark Blue', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 35,
    weight: 0.6,
    createdAt: '2024-02-08T10:00:00Z',
  },
  {
    id: '10',
    name: 'Running Shoes Pro',
    description:
      'Lightweight running shoes with responsive cushioning and breathable mesh upper.',
    price: 129.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    ],
    category: 'Footwear',
    brand: 'SpeedRun',
    variants: [
      {id: 'v40', type: 'size', name: 'Size', value: '8', priceModifier: 0, inStock: true},
      {id: 'v41', type: 'size', name: 'Size', value: '9', priceModifier: 0, inStock: true},
      {id: 'v42', type: 'size', name: 'Size', value: '10', priceModifier: 0, inStock: true},
      {id: 'v43', type: 'size', name: 'Size', value: '11', priceModifier: 0, inStock: true},
      {id: 'v44', type: 'color', name: 'Color', value: 'Red/Black', priceModifier: 0, inStock: true},
      {id: 'v45', type: 'color', name: 'Color', value: 'Blue/White', priceModifier: 0, inStock: true},
    ],
    inStock: true,
    stockCount: 45,
    dimensions: {width: 12, height: 5, depth: 4},
    weight: 0.6,
    createdAt: '2024-02-12T10:00:00Z',
  },
  {
    id: '11',
    name: 'Ceramic Coffee Mug Set',
    description:
      'Set of 4 handcrafted ceramic mugs. Microwave and dishwasher safe. 12oz capacity each.',
    price: 44.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400',
    ],
    category: 'Home',
    brand: 'ArtisanHome',
    variants: [
      {id: 'v46', type: 'color', name: 'Color', value: 'Earth Tones', priceModifier: 0, inStock: true},
      {id: 'v47', type: 'color', name: 'Color', value: 'Ocean Blue', priceModifier: 5, inStock: true},
      {id: 'v48', type: 'color', name: 'Color', value: 'Sunset', priceModifier: 5, inStock: true},
    ],
    inStock: true,
    stockCount: 20,
    weight: 1.0,
    createdAt: '2024-01-18T10:00:00Z',
  },
  {
    id: '12',
    name: 'Laptop Stand Adjustable',
    description:
      'Ergonomic aluminum laptop stand with adjustable height. Compatible with laptops up to 17 inches.',
    price: 69.99,
    currency: 'USD',
    imageUrls: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
    ],
    category: 'Electronics',
    brand: 'WorkSpace',
    variants: [
      {id: 'v49', type: 'color', name: 'Color', value: 'Silver', priceModifier: 0, inStock: true},
      {id: 'v50', type: 'color', name: 'Color', value: 'Space Gray', priceModifier: 10, inStock: true},
    ],
    inStock: true,
    stockCount: 30,
    dimensions: {width: 10, height: 9, depth: 2},
    weight: 0.8,
    createdAt: '2024-02-18T10:00:00Z',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat1',
    name: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    productCount: 4,
  },
  {
    id: 'cat2',
    name: 'Clothing',
    imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
    productCount: 2,
  },
  {
    id: 'cat3',
    name: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400',
    productCount: 2,
  },
  {
    id: 'cat4',
    name: 'Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1523779105320-d1cd346ff52b?w=400',
    productCount: 1,
  },
  {
    id: 'cat5',
    name: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    productCount: 2,
  },
  {
    id: 'cat6',
    name: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400',
    productCount: 1,
  },
];

export const mockUser: User = {
  id: 'user1',
  email: 'john.doe@example.com',
  firstName: 'John',
  lastName: 'Doe',
  phoneNumber: '+1 (555) 123-4567',
  dateJoined: '2023-06-15T10:00:00Z',
  isGuest: false,
  preferences: {
    newsletter: true,
    pushNotifications: true,
    biometricAuth: false,
    preferredCurrency: 'USD',
  },
  profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
};

export const mockAddresses: Address[] = [
  {
    id: 'addr1',
    firstName: 'John',
    lastName: 'Doe',
    street: '123 Main Street',
    street2: 'Apt 4B',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'United States',
    addressType: 'both',
    isDefault: true,
    phoneNumber: '+1 (555) 123-4567',
  },
  {
    id: 'addr2',
    firstName: 'John',
    lastName: 'Doe',
    street: '456 Oak Avenue',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90001',
    country: 'United States',
    addressType: 'shipping',
    isDefault: false,
    phoneNumber: '+1 (555) 987-6543',
  },
];

export const mockShippingMethods: ShippingMethod[] = [
  {
    id: 'ship1',
    name: 'Standard Shipping',
    description: 'Delivery in 5-7 business days',
    cost: 5.99,
    estimatedDays: 7,
    isAvailable: true,
    trackingIncluded: true,
  },
  {
    id: 'ship2',
    name: 'Express Shipping',
    description: 'Delivery in 2-3 business days',
    cost: 12.99,
    estimatedDays: 3,
    isAvailable: true,
    trackingIncluded: true,
  },
  {
    id: 'ship3',
    name: 'Next Day Delivery',
    description: 'Delivery by tomorrow',
    cost: 24.99,
    estimatedDays: 1,
    isAvailable: true,
    trackingIncluded: true,
  },
  {
    id: 'ship4',
    name: 'Free Shipping',
    description: 'Delivery in 7-10 business days',
    cost: 0,
    estimatedDays: 10,
    isAvailable: true,
    trackingIncluded: false,
  },
];
